# Generated by Django 5.2 on 2025-04-07 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=100)),
                (
                    "manufacturing_since",
                    models.IntegerField(help_text="Year when manufacturing started"),
                ),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PhoneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("launch_date", models.DateField()),
                (
                    "platform",
                    models.CharField(
                        help_text="OS platform (e.g., Android, iOS)", max_length=50
                    ),
                ),
                ("os_version", models.CharField(blank=True, max_length=50)),
                ("processor", models.CharField(blank=True, max_length=100)),
                ("ram", models.CharField(blank=True, max_length=50)),
                ("storage", models.CharField(blank=True, max_length=100)),
                ("display", models.CharField(blank=True, max_length=100)),
                ("camera", models.CharField(blank=True, max_length=100)),
                ("battery", models.CharField(blank=True, max_length=100)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="PhoneReview.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["-launch_date"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "date_published",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("author", models.CharField(max_length=100)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("pros", models.TextField(blank=True)),
                ("cons", models.TextField(blank=True)),
                (
                    "external_link",
                    models.URLField(
                        blank=True, help_text="Link to external review article"
                    ),
                ),
                (
                    "models",
                    models.ManyToManyField(
                        related_name="reviews", to="PhoneReview.phonemodel"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_published"],
            },
        ),
    ]
