# Generated by Django 5.2 on 2025-04-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_mock_data"),
        ("games", "0002_tags_alter_game_options_rename_genre_game_developer_and_more"),
    ]

    operations = []
